local utils = require('telescope-bibtex.utils')

describe("telescope-bibtex.utils", function()
    local root_dir = vim.fn.getcwd()

    local function run_test_in_dir(path, file_to_open, func)
        vim.cmd("cd " .. root_dir .. "/" .. path)
        vim.cmd("edit " .. file_to_open)
        local res = func()
        vim.cmd("cd " .. root_dir)
        return res
    end

    describe("parseLatex", function()
        it("returns nil when no bibs in latex/1", function()
            local res = run_test_in_dir("tests/latex/1", "main.tex", utils.parseLatex)
            assert.is_nil(res)
        end)
        
        it("finds bibs in latex/2", function()
            local res = run_test_in_dir("tests/latex/2", "main.tex", utils.parseLatex)
            assert.is_not_nil(res)
            assert.are.same(1, #res)
            assert.is_true(string.match(res[1], "bib%.bib$") ~= nil)
        end)
        
        it("finds multiple bibs in latex/3", function()
            local res = run_test_in_dir("tests/latex/3", "main.tex", utils.parseLatex)
            assert.is_not_nil(res)
            assert.are.same(2, #res)
        end)

        it("finds bibs when running from main2 in latex/4", function()
            local res = run_test_in_dir("tests/latex/4", "main2.tex", utils.parseLatex)
            assert.is_not_nil(res)
            assert.are.same(1, #res)
        end)

        it("Should not find commented out bibs in latex/5", function()
            local res = run_test_in_dir("tests/latex/5", "main2.tex", utils.parseLatex)
            assert.is_nil(res)
        end)
    end)

    describe("parseTypst", function()
        it("returns nil when no bibs in typst/1", function()
            local res = run_test_in_dir("tests/typst/1", "main.typ", utils.parseTypst)
            assert.is_nil(res)
        end)
        
        it("finds bibs in typst/2", function()
            local res = run_test_in_dir("tests/typst/2", "main.typ", utils.parseTypst)
            assert.is_not_nil(res)
            assert.are.same(1, #res)
        end)
        
        it("stops at first match in typst/3", function()
            local res = run_test_in_dir("tests/typst/3", "main.typ", utils.parseTypst)
            assert.is_not_nil(res)
            assert.are.same(1, #res)
        end)

        it("finds bibs when running from main2 in typst/4", function()
            local res = run_test_in_dir("tests/typst/4", "main2.typ", utils.parseTypst)
            assert.is_not_nil(res)
            assert.are.same(1, #res)
        end)

        it("finds bibs when running from main in typst/5", function()
            local res = run_test_in_dir("tests/typst/5", "main.typ", utils.parseTypst)
            assert.is_not_nil(res)
            assert.are.same(1, #res)
        end)

        it("Should not find commented out bibs in typst/6", function()
            local res = run_test_in_dir("tests/typst/6", "main.typ", utils.parseTypst)
            assert.is_nil(res)
        end)
    end)

    describe("parsePandoc", function()
        it("returns nil when no bibs in pandoc/1", function()
            local res = run_test_in_dir("tests/pandoc/1", "main.md", utils.parsePandoc)
            assert.is_nil(res)
        end)
        
        it("finds inline bib in pandoc/2", function()
            local res = run_test_in_dir("tests/pandoc/2", "main.md", utils.parsePandoc)
            assert.is_not_nil(res)
            assert.are.same(1, #res)
        end)
        
        it("finds list bibs in pandoc/3", function()
            local res = run_test_in_dir("tests/pandoc/3", "main.md", utils.parsePandoc)
            assert.is_not_nil(res)
            assert.are.same(2, #res)
        end)

        it("finds bibs when running from main2 in pandoc/4", function()
            local res = run_test_in_dir("tests/pandoc/4", "main2.md", utils.parsePandoc)
            assert.is_not_nil(res)
            assert.are.same(1, #res)
        end)

        it("Should not find commented out bibs in pandoc/5", function()
            local res = run_test_in_dir("tests/pandoc/5", "main2.md", utils.parsePandoc)
            assert.is_nil(res)
        end)
    end)
end)
